"use client";
import { Download } from "lucide-react";
import { motion } from "framer-motion";
import { useAuthStore } from "@/store/useAuthStore";
import { toast } from "sonner";

export default function BookingDetailsCard() {
  const { extraBookingDetails } = useAuthStore();

  const details = [
    { label: "Booking ID", key: "bookingId" },
    { label: "Hostel", key: "hostelName" },
    { label: "Room Type", key: "roomTitle" },
    { label: "Emergency Contact", key: "emergencyContactName" },
    { label: "Phone Number", key: "emergencyContactNumber" },
    { label: "Relation", key: "relation" },
    { label: "Has Medical Condition", key: "hasMedicalCondition" },
    { label: "Medical Condition", key: "medicalCondition" },
    { label: "Amount Due", key: "price", highlight: true },
  ];

  const handleDownload = () => {
    if (!extraBookingDetails || Object.keys(extraBookingDetails).length === 0)
      toast.error("No booking details to download.");
      return;

    const allDetails = Object.entries(extraBookingDetails)
      .map(([key, value]) => {
        const formattedKey = key
          .replace(/([A-Z])/g, " $1")
          .replace(/^./, (str) => str.toUpperCase());
        let formattedValue = value;
        if (typeof value === "boolean") formattedValue = value ? "Yes" : "No";
        return `${formattedKey}: ${formattedValue || "N/A"}`;
      })
      .join("\n");

    const content = [
      "📄 HOSTEL BOOKING FORM",
      "-------------------------",
      allDetails,
      "\n-------------------------",
      "Generated by Hostel Booking System",
      `Date: ${new Date().toLocaleString()}`,
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${
      extraBookingDetails.bookingId || "booking"
    }_${Date.now()}.txt`;
    link.click();
  };

  const hasDetails =
    extraBookingDetails && Object.keys(extraBookingDetails).length > 0;

  return (
    <motion.div
      initial={{ opacity: 0, y: 40 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      className="w-full md:w-1/2 bg-white rounded-3xl shadow-lg px-8 py-5 border border-gray-100"
    >
      <h2 className="font-bold text-xl mb-5 text-gray-800 border-b pb-2">
        Booking Details
      </h2>

      {hasDetails ? (
        <div className="space-y-1 text-gray-700">
          {details.map(({ label, key, highlight }) => {
            const value =
              key === "hasMedicalCondition"
                ? extraBookingDetails[key as keyof typeof extraBookingDetails]
                  ? "Yes"
                  : "No"
                : extraBookingDetails[key as keyof typeof extraBookingDetails] ||
                  "N/A";
            return (
              <motion.div
                key={key}
                whileHover={{ scale: 1.02, backgroundColor: "#f9fafb" }}
                transition={{ duration: 0.2 }}
                className={`flex justify-between items-center py-1 rounded-lg transition ${
                  highlight
                    ? "bg-green-50 font-semibold text-green-700"
                    : "hover:bg-gray-50"
                }`}
              >
                <span className="text-gray-600">{label}</span>
                <span>{value}</span>
              </motion.div>
            );
          })}

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleDownload}
            className="mt-5 text-sm md:text-base w-full cursor-pointer flex items-center justify-center gap-3 bg-green-600 hover:bg-green-700 text-white font-medium py-3 rounded-xl transition shadow-md"
          >
            <Download size={20} />
            Download Booking Form
          </motion.button>
        </div>
      ) : (
        <p className="text-gray-400 text-center py-6">
          No booking details available.
        </p>
      )}
    </motion.div>
  );
}
