"use client";
import { Download } from "lucide-react";
import { useAuthStore } from "@/store/useAuthStore";

export default function BookingDetailsCard() {
  const { extraBookingDetails } = useAuthStore();

  // Fields shown on the UI
  const details = [
    { label: "Booking ID", key: "bookingId" },
    { label: "Hostel", key: "hostelName" },
    { label: "Room Type", key: "roomTitle" },
    { label: "Emergency Contact", key: "emergencyContactName" },
    { label: "Contact Number", key: "emergencyContactNumber" },
    { label: "Relation", key: "relation" },
    { label: "Has Medical Condition", key: "hasMedicalCondition" },
    { label: "Medical Condition", key: "medicalCondition" },
    { label: "Amount Due", key: "price", highlight: true },
  ];

  const handleDownload = () => {
    if (!extraBookingDetails || Object.keys(extraBookingDetails).length === 0)
      return alert("No booking details to download.");

    // Include everything from the store for the downloaded file
    const allDetails = Object.entries(extraBookingDetails)
      .map(([key, value]) => {
        // Format key: convert camelCase → Normal Case
        const formattedKey = key
          .replace(/([A-Z])/g, " $1")
          .replace(/^./, (str) => str.toUpperCase());
        let formattedValue = value;

        if (typeof value === "boolean") {
          formattedValue = value ? "Yes" : "No";
        }

        return `${formattedKey}: ${formattedValue || "N/A"}`;
      })
      .join("\n");

    const content = [
      "📄 HOSTEL BOOKING FORM",
      "-------------------------",
      allDetails,
      "\n-------------------------",
      "Generated by Hostel Booking System",
      `Date: ${new Date().toLocaleString()}`,
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${
      extraBookingDetails.bookingId || "booking"
    }_${Date.now()}.txt`;
    link.click();
  };

  const hasDetails =
    extraBookingDetails && Object.keys(extraBookingDetails).length > 0;

  return (
    <div className="w-full md:w-1/2 bg-white rounded-2xl shadow-sm p-6">
      <h2 className="font-semibold mb-4 text-lg">Booking Details</h2>

      {hasDetails ? (
        <div className="space-y-2 text-sm text-gray-700">
          {details.map(({ label, key, highlight }) => (
            <p
              key={key}
              className={highlight ? "text-green-600 font-semibold" : ""}
            >
              <strong>{label}:</strong>{" "}
              {key === "hasMedicalCondition"
                ? extraBookingDetails[key as keyof typeof extraBookingDetails]
                  ? "Yes"
                  : "No"
                : extraBookingDetails[
                    key as keyof typeof extraBookingDetails
                  ] || "N/A"}
            </p>
          ))}

          <button
            onClick={handleDownload}
            className="flex cursor-pointer items-center justify-center gap-2 mt-6 w-full border border-green-600 rounded-lg py-2 hover:bg-green-50 transition"
          >
            <Download size={18} />
            <span>Download Booking Form</span>
          </button>
        </div>
      ) : (
        <p className="text-gray-500 text-sm">No booking details available.</p>
      )}
    </div>
  );
}
