// utils/printBookingDetails.ts
import { useAuthStore } from "@/store/useAuthStore";
import { Booking } from "@/types/bookingStatus";

/**
 * Generates a downloadable text file containing all booking + user details.
 * @param booking Optional Booking object to override roomNumber & arrivalDate
 */
export function printBookingDetails(booking?: Booking) {
  const { user, extraBookingDetails } = useAuthStore.getState();

  if (!extraBookingDetails || Object.keys(extraBookingDetails).length === 0) {
    return alert("No booking details available to download.");
  }

  // Merge user info and booking details
  const allDetails = [
    { label: "First Name", value: user?.firstName || "N/A" },
    { label: "Last Name", value: user?.lastName || "N/A" },
    { label: "Email", value: user?.email || "N/A" },
    { label: "Booking ID", value: extraBookingDetails.bookingId || "N/A" },
    { label: "Hostel", value: extraBookingDetails.hostelName || "N/A" },
    { label: "Room Type", value: extraBookingDetails.roomTitle || "N/A" },
    { label: "Price", value: extraBookingDetails.price || "N/A" },
    {
      label: "Room Number",
      value: booking?.roomNumber || "N/A",
    },
    {
      label: "Arrival Date",
      value: booking?.arrivalDate || "N/A",
    },
    {
      label: "Emergency Contact Name",
      value: extraBookingDetails.emergencyContactName || "N/A",
    },
    {
      label: "Emergency Contact Number",
      value: extraBookingDetails.emergencyContactNumber || "N/A",
    },
    { label: "Relation", value: extraBookingDetails.relation || "N/A" },
    {
      label: "Has Medical Condition",
      value: extraBookingDetails.hasMedicalCondition ? "Yes" : "No",
    },
    {
      label: "Medical Condition",
      value: extraBookingDetails.medicalCondition || "N/A",
    },
  ];

  // Format the details
  const content = [
    "📄 HOSTEL BOOKING DETAILS",
    "-------------------------",
    ...allDetails.map((d) => `${d.label}: ${d.value}`),
    "-------------------------",
    "Generated by Hostel Booking System",
    `Date: ${new Date().toLocaleString()}`,
  ].join("\n");

  // Trigger file download
  const blob = new Blob([content], { type: "text/plain" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${
    extraBookingDetails.bookingId || "booking"
  }_${Date.now()}.txt`;

  // Append to body first (some browsers require this)
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link); // clean up
}
